# Generated by Django 3.0.6 on 2020-06-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
    ]
