# Generated by Django 3.0.6 on 2020-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200608_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='size',
        ),
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='style',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='size',
            field=models.ManyToManyField(to='orders.Size', verbose_name='size'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ManyToManyField(to='orders.Size', verbose_name='size'),
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.ManyToManyField(to='orders.Size', verbose_name='size'),
        ),
    ]
