# Generated by Django 3.0.6 on 2020-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200608_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
